import type { CertificateData, MarkRow } from "@/types/certificate";

export const DEFAULT_SUBJECTS: MarkRow[] = [
  {
    paper: "1",
    subject: "FUNDAMENTAL OF COMPUTER",
    theoryMax: "100",
    theoryMin: "40",
    practicalMax: "50",
    practicalMin: "20",
    total: "138",
    grade: "A+",
  },
  {
    paper: "2",
    subject: "MS-OFFICE",
    theoryMax: "100",
    theoryMin: "40",
    practicalMax: "50",
    practicalMin: "20",
    total: "132",
    grade: "A",
  },
  {
    paper: "3",
    subject: "DTP",
    theoryMax: "100",
    theoryMin: "40",
    practicalMax: "50",
    practicalMin: "20",
    total: "140",
    grade: "A+",
  },
  {
    paper: "4",
    subject: "TALLY 7.2 & 9.0",
    theoryMax: "100",
    theoryMin: "40",
    practicalMax: "50",
    practicalMin: "20",
    total: "126",
    grade: "A",
  },
  {
    paper: "5",
    subject: "INTERNET",
    theoryMax: "100",
    theoryMin: "40",
    practicalMax: "50",
    practicalMin: "20",
    total: "135",
    grade: "A+",
  },
  {
    paper: "6",
    subject: "MS WINDOWS",
    theoryMax: "100",
    theoryMin: "40",
    practicalMax: "50",
    practicalMin: "20",
    total: "129",
    grade: "A",
  },
];

export const SAMPLE_CERTIFICATE: CertificateData = {
  documentType: "excellence",
  certificateNumber: "RCC-2026-0001",
  slNo: "001",
  rollNo: "RCC/2026/001",
  enrollmentNo: "RAMA-2026-001",
  studentName: "Rahul Kumar",
  fatherName: "Rajesh Kumar",
  courseCode: "ADCA-2026",
  courseName: "ADVANCE DIPLOMA IN COMPUTER APPLICATION",
  completionDate: "28 August 2026",
  trainingCenter: "Rama Coaching Center, Main Branch",
  centerCode: "RCC-001",
  performance: "A+",
  motherName: "Sunita Kumari",
  courseDuration: "12 Months",
  photoUrl: "",
  subjects: DEFAULT_SUBJECTS,
  dated: "28 August 2026",
  place: "Patna",
};
